CREATE TABLE jb178339.PASTA_RICE
(
    ID_number VARCHAR(100) CONSTRAINT PK2_ID_NUMBER PRIMARY KEY,
    pasta_riceName VARCHAR(100) NOT NULL,
    Price INTEGER NOT NULL CONSTRAINT CK_PASTA_RICE_PRICE CHECK (Price > 0),
    GRAIN VARCHAR(100),
);